max_line_length = 120
std = "lua51+wow_isiLive"

exclude_files = {
  "^%.git/",
  "^build/",
  "^libs/",
  "^Libs/",
  "^vendor/",
  "^externals/",
  "realm_language_data%.lua",
  "^realm_language_data%.lua$",
}

stds.wow_isiLive = {
  globals = {
    "IsiLiveDB",
    "SLASH_ISILIVE1",
    "SlashCmdList",
    "IsiLiveRealmLocaleByExactName",
    "IsiLiveRealmLocaleByNormalizedName",
  },
  read_globals = {
    "GetLocale",
    "CreateFrame",
    "UIParent",
    "GameTooltip",
    "DEFAULT_CHAT_FRAME",
    "print",
    "C_Timer",
    "C_AddOns",
    "C_Container",
    "C_Map",
    "C_QuestLog",
    "C_Spell",
    "C_Item",
    "UnitName",
    "UnitGUID",
    "GetTime",
    "InCombatLockdown",
    "IsAddOnLoaded",
    "GetAddOnMetadata",
    "hooksecurefunc",
    "SecureCmdOptionParse",
    "strtrim",
    "strsplit",
    "Enum",
    "UnitIsVisible",
    "UnitIsUnit",
    "CreateColor",
    "LE_PARTY_CATEGORY_INSTANCE",

    "C_ChallengeMode",
    "C_ChatInfo",
    "C_DamageMeter",
    "C_LFGList",
    "C_PaperDollInfo",
    "C_PartyInfo",
    "C_PlayerInfo",
    "C_SpellBook",

    "CanInspect",
    "CheckInteractDistance",
    "ClearInspectPlayer",
    "ClearOverrideBindings",
    "DoReadyCheck",
    "GetAverageItemLevel",
    "GetBindingAction",
    "GetInspectSpecialization",
    "GetInstanceInfo",
    "GetNumGroupMembers",
    "GetRealmName",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "InCombatLockdown",
    "IsInGroup",
    "IsInRaid",
    "LibStub",
    "NotifyInspect",
    "PlaySound",
    "SetOverrideBindingClick",
    "SOUNDKIT",
    "RAID_CLASS_COLORS",
    "UnitClass",
    "UnitExists",
    "UnitFullName",
    "UnitGroupRolesAssigned",
    "UnitIsGroupLeader",
  },
}
