-- GENERATED by tools/sync_mdt_forces.lua — do not edit by hand.
-- Data derived from MythicDungeonTools (GPLv2) by Nnoggie —
-- https://github.com/Nnoggie/MythicDungeonTools

local _, addonTable = ...

addonTable.MPlusForces = {
  season = "midnight_s2",
  mdtVersion = "6.2.15",
  sourceCommit = "1cbb06bab1bc3dbed091d1e1a5d2157e553c10a2",
  generatedAt = "2026-09-06",
  expiresAt = "2026-09-21",
  dungeonCount = 8,
  npcCount = 145,

  -- Enemy Forces total per dungeon (keyed by challenge-mode mapID)
  dungeonTotal = {
    [249] = { total = 608, name = "King's Rest" },
    [250] = { total = 687, name = "Temple of Sethraliss" },
    [399] = { total = 551, name = "Ruby Life Pools" },
    [584] = { total = 686, name = "The Blinding Vale" },
    [585] = { total = 738, name = "Voidscar Arena" },
    [586] = { total = 729, name = "Den of Nalorakk" },
    [587] = { total = 655, name = "Murder Row" },
    [588] = { total = 817, name = "Altar of Fangs" },
  },

  -- count per NPC-id (appears in one of the dungeons above)
  byNpcId = {
    [133935] = { count = 22, mapID = 249 }, -- Animated Guardian
    [134157] = { count = 5, mapID = 249 }, -- Umbral Warrior
    [134158] = { count = 25, mapID = 249 }, -- Shadow-Borne Champion
    [134174] = { count = 20, mapID = 249 }, -- Risen Hexer
    [134251] = { count = 10, mapID = 249 }, -- Seneschal M'bara
    [134331] = { count = 25, mapID = 249 }, -- King Rahu'ai
    [134364] = { count = 7, mapID = 250 }, -- Faithless Subjugator
    [134599] = { count = 7, mapID = 250 }, -- Imbued Stormcaller
    [134600] = { count = 7, mapID = 250 }, -- Sandswept Hunter
    [134602] = { count = 7, mapID = 250 }, -- Shrouded Fang
    [134616] = { count = 5, mapID = 250 }, -- Barbed Krolusk
    [134629] = { count = 25, mapID = 250 }, -- Sand-Sworn Rider
    [134686] = { count = 16, mapID = 250 }, -- Krolusk Matriarch
    [134691] = { count = 5, mapID = 250 }, -- Static Anomaly
    [134739] = { count = 25, mapID = 249 }, -- Purification Construct
    [134990] = { count = 7, mapID = 250 }, -- Storm Adept
    [134991] = { count = 25, mapID = 250 }, -- Sandfury Stonefist
    [135007] = { count = 25, mapID = 250 }, -- Orb Watcher
    [135167] = { count = 22, mapID = 249 }, -- Royal Berserker
    [135192] = { count = 5, mapID = 249 }, -- Honored Raptor
    [135204] = { count = 7, mapID = 249 }, -- Phantom Hex Priest
    [135231] = { count = 25, mapID = 249 }, -- Ghostly Brute
    [135239] = { count = 7, mapID = 249 }, -- Spectral Shaman
    [135562] = { count = 7, mapID = 250 }, -- Poisonous Viper
    [135846] = { count = 5, mapID = 250 }, -- Lightning Serpent
    [136076] = { count = 25, mapID = 250 }, -- Agitated Nimbus
    [136250] = { count = 25, mapID = 250 }, -- Twisted Hexxer
    [137473] = { count = 10, mapID = 249 }, -- Guard Captain Atu
    [137474] = { count = 25, mapID = 249 }, -- King Timalji
    [137478] = { count = 25, mapID = 249 }, -- Queen Wasi
    [137484] = { count = 25, mapID = 249 }, -- King A'akul
    [137485] = { count = 7, mapID = 249 }, -- Bloodsworn Assassin
    [137486] = { count = 25, mapID = 249 }, -- Queen Patlaa
    [137487] = { count = 10, mapID = 249 }, -- Skeletal Hunting Raptor
    [137969] = { count = 15, mapID = 249 }, -- Interment Construct
    [137989] = { count = 1, mapID = 249 }, -- Embalming Fluid
    [138489] = { count = 30, mapID = 249 }, -- Shadow of Zul
    [139110] = { count = 5, mapID = 250 }, -- Spark Channeler
    [139422] = { count = 7, mapID = 250 }, -- Dutiful Tamer
    [139425] = { count = 7, mapID = 250 }, -- Brood Tender
    [187897] = { count = 30, mapID = 399 }, -- Defier Draghar
    [187969] = { count = 5, mapID = 399 }, -- Deepstone Earthshaper
    [188011] = { count = 5, mapID = 399 }, -- Earthbound Guardian
    [188067] = { count = 7, mapID = 399 }, -- Flashfrost Chillweaver
    [188244] = { count = 25, mapID = 399 }, -- Primal Juggernaut
    [190034] = { count = 25, mapID = 399 }, -- Blazebound Destroyer
    [190206] = { count = 7, mapID = 399 }, -- Ashseer Flamelasher
    [190207] = { count = 7, mapID = 399 }, -- Primalist Cinderweaver
    [195119] = { count = 10, mapID = 399 }, -- Ruinous Stormbringer
    [197535] = { count = 30, mapID = 399 }, -- High Channeler Ryvati
    [197697] = { count = 40, mapID = 399 }, -- Flamegullet
    [197698] = { count = 48, mapID = 399 }, -- Thunderhead
    [197982] = { count = 5, mapID = 399 }, -- Storm Warrior
    [198047] = { count = 25, mapID = 399 }, -- Tempest Channeler
    [234849] = { count = 2, mapID = 587 }, -- Unleashed Imp
    [235257] = { count = 1, mapID = 587 }, -- Demon Fly
    [235261] = { count = 5, mapID = 587 }, -- Trained Felhunter
    [235265] = { count = 25, mapID = 587 }, -- Corrupted Warlock
    [235267] = { count = 5, mapID = 587 }, -- Wrathguard Flayer
    [235268] = { count = 7, mapID = 587 }, -- Fel Invoker
    [235322] = { count = 35, mapID = 587 }, -- Defiled Golem
    [235465] = { count = 25, mapID = 587 }, -- Shivan Punisher
    [236071] = { count = 25, mapID = 587 }, -- Bribed Guard
    [236073] = { count = 3, mapID = 587 }, -- Row Hooligan
    [236082] = { count = 6, mapID = 587 }, -- Seductive Sayaad
    [236084] = { count = 7, mapID = 587 }, -- Felonious Mage
    [236085] = { count = 1, mapID = 587 }, -- Felwyrm
    [236091] = { count = 3, mapID = 587 }, -- Street Sneak
    [236893] = { count = 2, mapID = 587 }, -- Warehouse Worker
    [236897] = { count = 7, mapID = 587 }, -- Keen Taskmaster
    [236902] = { count = 12, mapID = 587 }, -- Massive Felwyrm
    [236905] = { count = 30, mapID = 587 }, -- Felmaster Lucsei
    [238883] = { count = 7, mapID = 585 }, -- Dominated Brawler
    [241496] = { count = 7, mapID = 585 }, -- Enthralled Shaman
    [241808] = { count = 8, mapID = 586 }, -- Territorial Matriarch
    [241813] = { count = 5, mapID = 586 }, -- Thornclaw Gatherer
    [241814] = { count = 7, mapID = 586 }, -- Earthwhisper Tender
    [241816] = { count = 7, mapID = 586 }, -- Keen-Eyed Striker
    [241869] = { count = 28, mapID = 586 }, -- Avatar of Determination
    [241872] = { count = 9, mapID = 586 }, -- Frigid Mauler
    [241874] = { count = 5, mapID = 586 }, -- Frostfang
    [241876] = { count = 7, mapID = 586 }, -- Glacial Revenant
    [241911] = { count = 7, mapID = 586 }, -- Terra Rumbler
    [243736] = { count = 1, mapID = 585 }, -- Blistercreep
    [243766] = { count = 7, mapID = 585 }, -- Kilivore Screamer
    [243835] = { count = 5, mapID = 585 }, -- Savage Shredclaw
    [243983] = { count = 4, mapID = 585 }, -- Sycophantic Tarasek
    [243985] = { count = 5, mapID = 585 }, -- Longtooth Tuskarr
    [243988] = { count = 4, mapID = 585 }, -- Feral Saberon
    [243996] = { count = 4, mapID = 585 }, -- Lost Sethrak
    [244260] = { count = 25, mapID = 585 }, -- Chitigoth
    [244309] = { count = 25, mapID = 585 }, -- Brutok
    [244708] = { count = 7, mapID = 585 }, -- Voidminder
    [244889] = { count = 35, mapID = 586 }, -- Loa Speaker Nanea
    [245139] = { count = 7, mapID = 586 }, -- Stormbound Mystic
    [245143] = { count = 5, mapID = 586 }, -- Ruthless Totemcaller
    [245145] = { count = 6, mapID = 586 }, -- Bonded Beasttamer
    [245146] = { count = 25, mapID = 586 }, -- Grizzled Warbringer
    [245190] = { count = 5, mapID = 586 }, -- Loyal Saberfang
    [245336] = { count = 7, mapID = 584 }, -- Radiant Spellsower
    [245339] = { count = 6, mapID = 584 }, -- Underbrush Stalker
    [245345] = { count = 7, mapID = 584 }, -- Lightgorged Lasher
    [245346] = { count = 20, mapID = 584 }, -- Virid Grovekeeper
    [245410] = { count = 1, mapID = 584 }, -- Lasher
    [245460] = { count = 7, mapID = 584 }, -- Leafy Grovecrawler
    [245473] = { count = 5, mapID = 584 }, -- Thorny Saptor
    [245484] = { count = 7, mapID = 584 }, -- Lightfeather Petalwing
    [245513] = { count = 25, mapID = 584 }, -- Overgrown Hydra
    [245527] = { count = 1, mapID = 584 }, -- Spineshield Beetle
    [245752] = { count = 7, mapID = 586 }, -- Keen-Eyed Striker
    [245855] = { count = 25, mapID = 586 }, -- Spirit of Hunger
    [245950] = { count = 65, mapID = 585 }, -- Watchful Harrower
    [246871] = { count = 22, mapID = 584 }, -- Luminous Thornmaw
    [249461] = { count = 5, mapID = 585 }, -- Abducted Drakonid
    [249590] = { count = 8, mapID = 585 }, -- Angry Krolusk
    [249603] = { count = 5, mapID = 585 }, -- Protective Turtle
    [249608] = { count = 5, mapID = 585 }, -- Raging Raptor
    [249756] = { count = 60, mapID = 584 }, -- Potatoad Matriarch
    [250478] = { count = 50, mapID = 586 }, -- The Winter Squall
    [252053] = { count = 25, mapID = 585 }, -- Brutal Overseer
    [252072] = { count = 25, mapID = 585 }, -- Voidtouched Magi
    [252508] = { count = 1, mapID = 585 }, -- Scavenging Siphoid
    [252529] = { count = 35, mapID = 587 }, -- Bribed Captain
    [254850] = { count = 25, mapID = 584 }, -- Sporeblight Belcher
    [255604] = { count = 6, mapID = 587 }, -- Seductive Sayaad
    [261550] = { count = 1, mapID = 588 }, -- Venom Leech
    [261552] = { count = 5, mapID = 588 }, -- Bloodletter
    [261553] = { count = 5, mapID = 588 }, -- Ravenous Descendant
    [261554] = { count = 25, mapID = 588 }, -- Twinfang Harrower
    [261557] = { count = 7, mapID = 588 }, -- High Evolutionist
    [261560] = { count = 7, mapID = 588 }, -- Primal Serpent
    [261573] = { count = 30, mapID = 588 }, -- Ascendant Serpent
    [262011] = { count = 25, mapID = 588 }, -- Rattling Writhe
    [263109] = { count = 25, mapID = 588 }, -- Ula'tek's Chosen
    [263112] = { count = 1, mapID = 588 }, -- Living Venom
    [263228] = { count = 25, mapID = 585 }, -- Agitated Voidscythe
    [265057] = { count = 5, mapID = 250 }, -- Spark Channeler
    [267545] = { count = 40, mapID = 585 }, -- Aegyra the Unyielding
    [267546] = { count = 40, mapID = 585 }, -- Raj'kess the Spellstorm
    [268184] = { count = 30, mapID = 585 }, -- Devouring Brutalizer
    [268317] = { count = 5, mapID = 250 }, -- Faithless Tormentor
    [269227] = { count = 5, mapID = 250 }, -- Temple Disruptor
    [270306] = { count = 25, mapID = 588 }, -- Ritual Chieftain
    [270502] = { count = 7, mapID = 249 }, -- Half-Finished Mummy
    [271453] = { count = 5, mapID = 588 }, -- Blade of the Altar
  },
}
