-- GENERATED by tools/sync_mdt_forces.lua — do not edit by hand.
-- Data derived from MythicDungeonTools (GPLv2) by Nnoggie —
-- https://github.com/Nnoggie/MythicDungeonTools

local _, addonTable = ...

addonTable.MPlusForces = {
  season = "midnight_s1",
  mdtVersion = "6.2.9",
  sourceCommit = "a49bd78f843bb89d2cea3daefbc1cf7aed809c31",
  generatedAt = "2026-08-27",
  expiresAt = "2026-09-11",
  dungeonCount = 8,
  npcCount = 127,

  -- Enemy Forces total per dungeon (keyed by challenge-mode mapID)
  dungeonTotal = {
    [161] = { total = 431, name = "Skyreach" },
    [239] = { total = 568, name = "Seat of the Triumvirate" },
    [402] = { total = 460, name = "Algethar Academy" },
    [556] = { total = 643, name = "Pit of Saron" },
    [557] = { total = 591, name = "Windrunner Spire" },
    [558] = { total = 585, name = "Magisters Terrace" },
    [559] = { total = 596, name = "Nexus Point Xenas" },
    [560] = { total = 607, name = "Maisara Caverns" },
  },

  -- count per NPC-id (appears in one of the dungeons above)
  byNpcId = {
    [75976] = { count = 1, mapID = 161 }, -- Lowborn Servant
    [76087] = { count = 12, mapID = 161 }, -- Solar Construct
    [76132] = { count = 5, mapID = 161 }, -- Soaring Chakram Master
    [76149] = { count = 15, mapID = 161 }, -- Dread Raven
    [76154] = { count = 5, mapID = 161 }, -- Suntalon Tamer
    [76205] = { count = 5, mapID = 161 }, -- Outcast Warrior
    [78932] = { count = 7, mapID = 161 }, -- Driving Gale-Caller
    [78933] = { count = 15, mapID = 161 }, -- Solar Elemental
    [79093] = { count = 2, mapID = 161 }, -- Suntalon
    [79303] = { count = 12, mapID = 161 }, -- Adorned Bladetalon
    [79462] = { count = 5, mapID = 161 }, -- Blinding Sun Priestess
    [79466] = { count = 7, mapID = 161 }, -- Initiate of the Rising Sun
    [79467] = { count = 7, mapID = 161 }, -- Adept of the Dawn
    [122322] = { count = 1, mapID = 239 }, -- Famished Broken
    [122403] = { count = 3, mapID = 239 }, -- Shadowguard Champion
    [122404] = { count = 8, mapID = 239 }, -- Dire Voidbender
    [122405] = { count = 7, mapID = 239 }, -- Dark Conjurer
    [122413] = { count = 9, mapID = 239 }, -- Ruthless Riftstalker
    [122421] = { count = 15, mapID = 239 }, -- Umbral War-Adept
    [122423] = { count = 15, mapID = 239 }, -- Grand Shadow-Weaver
    [122571] = { count = 20, mapID = 239 }, -- Rift Warden
    [124171] = { count = 10, mapID = 239 }, -- Merciless Subjugator
    [192329] = { count = 2, mapID = 402 }, -- Territorial Eagle
    [192333] = { count = 15, mapID = 402 }, -- Alpha Eagle
    [192680] = { count = 18, mapID = 402 }, -- Guardian Sentry
    [196044] = { count = 4, mapID = 402 }, -- Unruly Textbook
    [196045] = { count = 5, mapID = 402 }, -- Corrupted Manafiend
    [196200] = { count = 15, mapID = 402 }, -- Algeth'ar Echoknight
    [196202] = { count = 5, mapID = 402 }, -- Spectral Invoker
    [196577] = { count = 5, mapID = 402 }, -- Spellbound Battleaxe
    [196671] = { count = 15, mapID = 402 }, -- Vicious Ravager
    [196694] = { count = 4, mapID = 402 }, -- Arcane Forager
    [197219] = { count = 9, mapID = 402 }, -- Vile Lasher
    [197398] = { count = 2, mapID = 402 }, -- Hungry Lasher
    [197406] = { count = 4, mapID = 402 }, -- Aggravated Skitterfly
    [232056] = { count = 7, mapID = 557 }, -- Territorial Dragonhawk
    [232063] = { count = 15, mapID = 557 }, -- Apex Lynx
    [232067] = { count = 7, mapID = 557 }, -- Creeping Spindleweb
    [232070] = { count = 7, mapID = 557 }, -- Restless Steward
    [232071] = { count = 4, mapID = 557 }, -- Dutiful Groundskeeper
    [232106] = { count = 1, mapID = 558 }, -- Brightscale Wyrm
    [232113] = { count = 15, mapID = 557 }, -- Spellguard Magus
    [232116] = { count = 5, mapID = 557 }, -- Windrunner Soldier
    [232119] = { count = 7, mapID = 557 }, -- Swiftshot Archer
    [232122] = { count = 15, mapID = 557 }, -- Phalanx Breaker
    [232146] = { count = 15, mapID = 557 }, -- Phantasmal Mystic
    [232147] = { count = 6, mapID = 557 }, -- Lingering Marauder
    [232148] = { count = 7, mapID = 557 }, -- Spectral Axethrower
    [232171] = { count = 6, mapID = 557 }, -- Ardent Cutthroat
    [232173] = { count = 5, mapID = 557 }, -- Fervent Apothecary
    [232175] = { count = 15, mapID = 557 }, -- Devoted Woebringer
    [232176] = { count = 20, mapID = 557 }, -- Flesh Behemoth
    [232232] = { count = 4, mapID = 557 }, -- Zealous Reaver
    [232283] = { count = 5, mapID = 557 }, -- Loyal Worg
    [232369] = { count = 7, mapID = 558 }, -- Arcane Magister
    [234062] = { count = 16, mapID = 558 }, -- Arcane Sentry
    [234064] = { count = 7, mapID = 558 }, -- Dreadful Voidwalker
    [234065] = { count = 5, mapID = 558 }, -- Hollowsoul Shredder
    [234066] = { count = 12, mapID = 558 }, -- Devouring Tyrant
    [234068] = { count = 12, mapID = 558 }, -- Shadowrift Voidcaller
    [234069] = { count = 1, mapID = 558 }, -- Voidling
    [234089] = { count = 2, mapID = 558 }, -- Animated Codex
    [234124] = { count = 5, mapID = 558 }, -- Sunblade Enforcer
    [234486] = { count = 5, mapID = 558 }, -- Lightward Healer
    [234673] = { count = 1, mapID = 557 }, -- Spindleweb Hatchling
    [236894] = { count = 17, mapID = 557 }, -- Bloated Lasher
    [238049] = { count = 5, mapID = 557 }, -- Scouting Trapper
    [238099] = { count = 1, mapID = 557 }, -- Pesty Lashling
    [240973] = { count = 12, mapID = 558 }, -- Runed Spellbreaker
    [241354] = { count = 1, mapID = 558 }, -- Void-Infused Brightscale
    [241642] = { count = 15, mapID = 559 }, -- Lingering Image
    [241643] = { count = 5, mapID = 559 }, -- Shadowguard Defender
    [241644] = { count = 5, mapID = 559 }, -- Corewright Arcanist
    [241645] = { count = 3, mapID = 559 }, -- Hollowsoul Scrounger
    [241647] = { count = 7, mapID = 559 }, -- Flux Engineer
    [241660] = { count = 15, mapID = 559 }, -- Duskfright Herald
    [242964] = { count = 7, mapID = 560 }, -- Keen Headhunter
    [248373] = { count = 15, mapID = 559 }, -- Circuit Seer
    [248501] = { count = 1, mapID = 559 }, -- Reformed Voidling
    [248502] = { count = 15, mapID = 559 }, -- Null Sentinel
    [248506] = { count = 8, mapID = 559 }, -- Dreadflail
    [248678] = { count = 15, mapID = 560 }, -- Hulking Juggernaut
    [248684] = { count = 5, mapID = 560 }, -- Frenzied Berserker
    [248685] = { count = 7, mapID = 560 }, -- Ritual Hexxer
    [248686] = { count = 15, mapID = 560 }, -- Dread Souleater
    [248690] = { count = 2, mapID = 560 }, -- Grim Skirmisher
    [248692] = { count = 2, mapID = 560 }, -- Reanimated Warrior
    [248693] = { count = 1, mapID = 560 }, -- Mire Laborer
    [248706] = { count = 3, mapID = 559 }, -- Cursed Voidcaller
    [248708] = { count = 7, mapID = 559 }, -- Nexus Adept
    [249002] = { count = 2, mapID = 560 }, -- Warding Mask
    [249020] = { count = 3, mapID = 560 }, -- Hexbound Eagle
    [249022] = { count = 5, mapID = 560 }, -- Bramblemaw Bear
    [249024] = { count = 15, mapID = 560 }, -- Hollow Soulrender
    [249025] = { count = 15, mapID = 560 }, -- Bound Defender
    [249030] = { count = 15, mapID = 560 }, -- Restless Gnarldin
    [249036] = { count = 7, mapID = 560 }, -- Tormented Shade
    [249086] = { count = 7, mapID = 558 }, -- Void Terror
    [250992] = { count = 1, mapID = 161 }, -- Raging Squall
    [251853] = { count = 7, mapID = 559 }, -- Grand Nullifier
    [251861] = { count = 12, mapID = 558 }, -- Blazing Pyromancer
    [252551] = { count = 15, mapID = 556 }, -- Deathwhisper Necrolyte
    [252555] = { count = 6, mapID = 556 }, -- Lumbering Plaguehorror
    [252558] = { count = 5, mapID = 556 }, -- Rotting Ghoul
    [252559] = { count = 2, mapID = 556 }, -- Leaping Geist
    [252561] = { count = 5, mapID = 556 }, -- Quarry Tormentor
    [252563] = { count = 15, mapID = 556 }, -- Dreadpulse Lich
    [252564] = { count = 20, mapID = 556 }, -- Glacieth
    [252565] = { count = 5, mapID = 556 }, -- Wrathbone Enforcer
    [252566] = { count = 7, mapID = 556 }, -- Rimebone Coldwraith
    [252567] = { count = 7, mapID = 556 }, -- Gloombound Shadebringer
    [252606] = { count = 6, mapID = 556 }, -- Plungetalon Gargoyle
    [252610] = { count = 11, mapID = 556 }, -- Ymirjar Graveblade
    [252756] = { count = 15, mapID = 239 }, -- Void-Infused Destroyer
    [253302] = { count = 15, mapID = 560 }, -- Hex Guardian
    [253458] = { count = 7, mapID = 560 }, -- Zaib'yan
    [253473] = { count = 5, mapID = 560 }, -- Gloomwing Bat
    [253683] = { count = 10, mapID = 560 }, -- Rokh'zal
    [254740] = { count = 5, mapID = 560 }, -- Umbral Shadowbinder
    [254926] = { count = 7, mapID = 559 }, -- Lightwrought
    [254928] = { count = 3, mapID = 559 }, -- Flarebat
    [254932] = { count = 2, mapID = 559 }, -- Radiant Swarm
    [255320] = { count = 8, mapID = 239 }, -- Ravenous Umbralfin
    [257190] = { count = 9, mapID = 556 }, -- Iceborn Proto-Drake
    [257447] = { count = 5, mapID = 558 }, -- Hollowsoul Shredder
    [258868] = { count = 4, mapID = 557 }, -- Haunting Grunt
    [259387] = { count = 1, mapID = 558 }, -- Spellwoven Familiar
  },
}
